disable update of mu to 1.12.13 for now due to scm check error
details of error:

.....
49/49 test-scm              FAIL            3.90s   exit status 2
>>> UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 MALLOC_PERTURB_=202 /tmp/guix-build-mu-1.12.13.drv-0/build/scm/test-scm
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
TAP version 14
1..1
%%%% Starting test mu-scm-tests  (Writing full log to "mu-scm-tests.log")
/tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm-test.scm:176: FAIL
/tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm-test.scm:181: FAIL
stderr:
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm.scm
;;; compiled /tmp/guix-build-mu-1.12.13.drv-0/mu-tmp-7H0CF3/guile/ccache/3.0-LE-8-4.6/tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm.scm.go
;;; compiling /tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm-test.scm
;;; compiled /tmp/guix-build-mu-1.12.13.drv-0/mu-tmp-7H0CF3/guile/ccache/3.0-LE-8-4.6/tmp/guix-build-mu-1.12.13.drv-0/source/scm/mu-scm-test.scm.go
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Summary of Failures:

49/49 test-scm              FAIL            3.90s   exit status 2

Ok:                48
Fail:              1

Full log written to /tmp/guix-build-mu-1.12.13.drv-0/build/meson-logs/testlog.txt
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "meson" arguments: ("test" "--print-errorlogs" "-t" "0") exit-status: 1 term-signal: #f stop-signal: #f>